services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    networks:
      - internal
    depends_on:
      - login
      - api
      - gameserver
    env_file:
      - ./.env
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: xadrez-dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432" #TODO: remove this port
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back/db-schemas/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
  redis:
    image: redis:8
    ports:
      - "6379:6379" #TODO: remove this port
    volumes:
      - redis_data:/data
    networks:
      - internal
  login:
    build:
      context: ./back
      dockerfile: ./Dockerfile.login
      args:
        PORT: ${PORT_LOGIN}
    networks:
      - internal
    env_file:
      - ./.env
    depends_on:
      - api
      - auth
    develop:
      watch:
        - action: rebuild
          path: ./back
          target: /app
          ignore: 
            - ./back/.git
            - ./back/.gitignore
            - ./back/bin
            - ./back/db-schemas
          
  api:
    build:
      context: ./back
      dockerfile: ./Dockerfile.api
      args:
        PORT: ${PORT_API}
    networks:
      - internal
    env_file:
      - ./.env
    depends_on:
      - postgres
      - auth
    develop:
      watch:
        - action: rebuild
          path: ./back
          target: /app
          ignore: 
            - ./back/.git
            - ./back/.gitignore
            - ./back/bin
            - ./back/db-schemas
  gameserver:
    build:
      context: ./back
      dockerfile: ./Dockerfile.game-server
      args:
        PORT_WS: ${PORT_GAMESERVER}
        PORT_GRPC_MATCHMAKING: ${INTERNAL_PORT_GAMESERVER_GRPC_MATCHMAKING}
    env_file:
      - ./.env
    depends_on:
      - postgres
      - auth
    networks:
      - internal
    develop:
      watch:
        - action: rebuild
          path: ./back
          target: /app
          ignore: 
            - ./back/.git
            - ./back/.gitignore
            - ./back/bin
            - ./back/db-schemas
  auth:
    build:
      context: ./back
      dockerfile: ./Dockerfile.auth
      args:
        PORT: ${INTERNAL_PORT_AUTH_GRPC}
    networks:
      - internal
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    develop:
      watch:
        - action: rebuild
          path: ./back
          target: /app
          ignore: 
            - ./back/.git
            - ./back/.gitignore
            - ./back/bin
            - ./back/db-schemas
  front:
    build: ./front
    networks:
      - internal
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app
          ignore:
            - ./front/node_modules/
            - ./front/.git/
        - action: rebuild
          path: ./front/package.json
    depends_on:
      - login
      - gameserver
      - api

volumes:
  postgres_data:
  redis_data:

networks:
  internal:
    driver: bridge