services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: xadrez-dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432" #TODO: remove this port
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back/db-schemas/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
  redis:
    image: redis:8
    ports:
      - "6379:6379" #TODO: remove this port
    volumes:
      - redis_data:/data
    networks:
      - internal
  login:
    build:
      context: ./back
      dockerfile: ./Dockerfile.login
    ports:
      - "8085:8085"
    networks:
      - internal
  api:
    build:
      context: ./back
      dockerfile: ./Dockerfile.api
    ports:
      - "8080:8080"
    networks:
      - internal
  gameserver:
    build:
      context: ./back
      dockerfile: ./Dockerfile.game-server
    ports:
      - "8082:8082"
      - "9191:9191" #TODO: remove this port
    networks:
      - internal
  auth:
    build:
      context: ./back
      dockerfile: ./Dockerfile.auth
    ports:
      - "8989:8989" #TODO: remove this port
    networks:
      - internal
    depends_on:
      - postgres
      - redis
    env_file:
      - ./back/.env
  front:
    build: ./front
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app
          ignore:
            - ./front/node_modules/
            - ./front/.git/
        - action: rebuild
          path: ./front/package.json

volumes:
  postgres_data:
  redis_data:

networks:
  internal:
    driver: bridge